security:
  jwt:
    token:
      secret: ${JWT_SECRET}
      expire-length: ${JWT_EXPIRE_TIME:3600000}

spring:
  application:
    name: jogatinastore
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
      #dialect: org.hibernate.dialect.MySQL8Dialect or MySQLDialect
    show-sql: false

    open-in-view: false

# server:
  # error: # Redundant after Global Exceptions Implementation
    # include-stacktrace: never
    # include-message: never
    # include-binding-errors: never
    # include-exception: false