CREATE TABLE users (
   id CHAR(36) PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   cpf VARCHAR(20) NOT NULL,
   birth_date DATE,
   phone_number VARCHAR(20),
   email VARCHAR(255) NOT NULL UNIQUE,
   password_hash VARCHAR(255) NOT NULL,
   hash VARCHAR(255),
   is_active BOOLEAN DEFAULT TRUE,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);