package br.com.jogatinastore.infra.exception.code;

public enum ErrorCode {
    INVALID_PATH_PARAMETER,
    BAD_CREDENTIALS,
    ITEM_UNAVAILABLE,
    ALREADY_EXISTS,
    INTERNAL_ERROR,
    INVALID_JSON_BODY,
    INVALID_TOKEN,
    NOT_FOUND,
    NOT_AUTHORIZED,
    INSUFFICIENT_STOCK,
    VALIDATION_ERROR,
}